### PR TITLE
feat: Support https_proxy environment variable - https-proxy-agent included in the bundle

### PR DESCRIPTION
**Pull request by aveiga**

### CODE REVIEW

**Comment by aveiga** [comment]
@adamdbradley this contains all the fixes from @RS-Sautter plus https-proxy-agent is now part of the final bundle. Can this be merged?

**Comment by fr1zle** [comment]
Is there anything one can do to get this or a similiar fix merged? Not working behind a corporate proxy really is a big show stopper.

**Comment by adamdbradley** [comment]
Can this be updated so https-proxy-agent is instead bundled? We prefer this so we don't have dependency issues down the road, and to have a faster npm install and load time.

**Comment by sajTempler** [comment]
@manucorporat 
This would help a lot

**Pull request merged**
