### PR TITLE
feat: Support https_proxy environment variable

### PR DESCRIPTION
**Pull request by RS-Sautter**
In order for the stencil creator to work behind a corporate proxy it is necessary to read and use the https_proxy environment variable when issuing requests to "the outside world".

### CODE REVIEW

**Comment by RS-Sautter** [comment]
Solves issue #16.

**Comment by RS-Sautter** [comment]
@manucorporat I updated this PR and removed conflicts. Please merge! :)

**Comment by JohannesBayerAlbert** [comment]
Can this be merged please?

**Comment by RS-Sautter** [comment]
We see more and more people, who need this feature. Please merge soon!

**Comment by tobias-ziegler** [comment]
Just ran into this issue, please merge 😄

**Comment by adamdbradley** [comment]
Could this be updated so `https-proxy-agent` gets bundled with the final output?

**Comment by aveiga** [comment]
@RS-Sautter, are you still interested in contributing to this issue?

**Comment by RS-Sautter** [comment]
@aveiga I have already contributed. It was not merged.

**Comment by aveiga** [comment]
Hi @RS-Sautter, sorry if my tone seemed harsh. I really am needing your fix, as this issue is a blocker to promote Stencil in my company. I suppose @adamdbradley does work in Stencil, do you think you can accommodate for his request?

**Comment by aveiga** [comment]
@adamdbradley `http-proxy-agent` is now part of the bundle here: https://github.com/ionic-team/create-stencil/pull/31

**Comment by adamdbradley** [comment]
Merged in the followup PR #31 

thanks!

**Pull request closed without merging**
